' CST true near-field monitor workpack template for CS-202614
' Generated by code\prepare_cst_true_nearfield_workpack.py
'
' This is a CST operator skeleton. CST API names differ by version, so keep the
' CSV contract stable and adapt only the CST-specific result-tree calls.

Option Explicit

Const CASE_CSV = "data\cst_true_nearfield_workpack\true_nearfield_monitor_cases.csv"
Const SENSOR_SHELL_CSV = "data\cst_true_nearfield_workpack\true_nearfield_sensor_shell.csv"
Const EXPORT_CONTRACT_CSV = "data\cst_true_nearfield_workpack\true_nearfield_export_contract.csv"

Sub Main()
    MsgBox "Use " & CASE_CSV & " and " & SENSOR_SHELL_CSV & " as the authoritative true near-field monitor workpack." & vbCrLf & _
           "Run required Level 1 z-dipole cases first, then compare against the FarfieldPlot-derived baseline."
End Sub

Sub BuildTrueNearfieldMonitor(ByVal sampleId, ByVal freqHz, ByVal monitorName)
    ' Suggested CST workflow:
    ' 1. Open or clone the Level 1 source project for sampleId.
    ' 2. Ensure units are meters and the solver/export frequency equals freqHz.
    ' 3. Add a true E-field near-field monitor at freqHz.
    ' 4. After solving, sample/interpolate the monitor at SENSOR_SHELL_CSV coordinates.
    ' 5. Export one row per sensor_id and Cartesian component Ex/Ey/Ez.
    ' 6. Keep the export columns listed in EXPORT_CONTRACT_CSV.
    AddToHistory "CS202614_TrueNearfield_Metadata", "' sample_id=" & sampleId & ", frequency_hz=" & CStr(freqHz) & ", monitor=" & monitorName
End Sub
